### ISSUE TITLE
getCredentials vs getCurrentToken

### ISSUE THREAD

**Issue by poyannabati** [magus/react-native-facebook-login#55]
Hey, 

Thanks for the effort to build this component, I appreciate it! 

Just noticed the APIs are different for Android and iOS. Is this by design? FBLoginManager.getCredentials on iOS and FBLoginManager.getCurrentToken for Android. Are there any plans of unifying this API?

**Comment by poyannabati** [comment]
Initially was a bit too hasty with the filing of the issue, but I've updated it now :)

**Comment by lwhiteley** [comment]
can someone here volunteer to test the mentioned PR
and see if this issue is properly resolved for Android

Please continue the conversation in the Pull Request 

https://github.com/magus/react-native-facebook-login/pull/105

[install from my fork directly to test (using github url)]

please see the updated docs on to reference changes for your issue. 
If not there please suggest it in the PR

**Comment by lwhiteley** [comment]
issue resolved by #105

**Comment by jpgarcia** [comment]
@lwhiteley The API is still broken between iOS and Android. Shall we consider to reopen this?

```javascript
// iOS
FBLoginManager.getCredentials((err, data) => {
})

// Android
FBLoginManager.getCredentials(data => {
})
```

**Comment by lwhiteley** [comment]
3b14cf58d8104a81f71bd8f071995eef9a819ce0

fixed with the above hash

**Comment by jpgarcia** [comment]
Will use this hash till you publish a new version. thanks!

**Comment by lwhiteley** [comment]
use master, there was a merge error that i resolved after 👍
