### ISSUE TITLE
undefined is not an object (evaluating 'FBLoginManager.getCurrentToken')

### ISSUE THREAD

**Issue by Beatsleigher** [magus/react-native-facebook-login#85]
I'm constantly getting the above mentioned error in my Android app, written with react-native.

I've tried this on several different devices, both with the same results.

I followed the instructions as mentioned in the Android readme file, but to no avail. The FBLogin simply isn't working.

Here is the relevant code from my index.android.js:
`
var {NativeModules} = require('react-native');
var FBLogin = require('react-native-facebook-login');
var FBLoginManager = NativeModules.FBLoginManager;

renderFacebookLogin() {
      return (
        <View style={styles.container}>
            <FBLogin />
          </View>
      );
  }
`

I have added all the dependencies to the files listed in the Android readme.

Any help with this issue is much appreciated.

**Comment by skyride99** [comment]
I have the same problem!

**Comment by apastel** [comment]
I believe I'm having the same issue.
`undefined is not an object (evaluating FBLoginManager.LoginBehaviors.Native)`

I've followed the instructions in the Android setup and I've copied and pasted the exact code from the "Exhaustive" example in the README.

**Comment by bsy** [comment]
+1

**Comment by Beatsleigher** [comment]
I forgot to mention that I fixed the issue.

Every time you add a new module, kill the JS server and run
react-native run-android.
That will recompile the project and will build all dependencies. The JS server will also be restarted.

**Comment by bsy** [comment]
@Beatsleigher restarting the packager and re-running `react-native run-android` didn't fix it for me.. were there any other steps that you took outside of the readme?

**Comment by lwhiteley** [comment]
maybe you should check if you are running the latest version of watchman

also you can run `watchman watch-del-all` or delete a specific directory
its watching to clear the cache of watchman

then run the packager again

On Wed, 2 Mar 2016 at 14:39 Ben Yee <notifications@github.com> wrote:

> @Beatsleigher <https://github.com/Beatsleigher> restarting the packager
> and re-running react-native run-android didn't fix it for me.. were there
> any other steps that you took outside of the readme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magus/react-native-facebook-login/issues/85#issuecomment-191365833>
> .
>
-- 
_______________
Regards
Layton Whiteley

**Comment by bsy** [comment]
@lwhiteley upgrading watchman was it! thanks!

**Comment by apastel** [comment]
Upgrading watchman was not it for me, unfortunately.
Upgraded from v4.4.0 to v4.5.0 and still getting this error.
Also tried deleting my node_modules and re-running `npm install`.

**Comment by lwhiteley** [comment]
are you trying to use `FBLoginManager.LoginBehaviors.Native` for android?

**Comment by apastel** [comment]
Yes, as in the example. 

Though admittedly I'm not sure what that buys me.

**Comment by lwhiteley** [comment]
Oh i see, i dont think it was implemented for android as yet. 

I havent had time to update some of these quirks yet.

The implementation will use native by default or go to web if the facebook app is not present. atleast thats how i remember it working.

so you're getting that error because its really not there.

if you really need it, create an issue or a pull request

**Comment by Beatsleigher** [comment]
The module works just fine. As I said, what fixed it for me, was restarting the package and rebuilding.
Basically, I killed the server, and re-ran react-native run-android.

**Comment by lwhiteley** [comment]
thats great @Beatsleigher, however, @apastel has a different issue. he was trying to access a feature that isnt there yet.
thanks

**Comment by apastel** [comment]
Well, looks like I'm still having this issue with other function calls:
`undefined is not a function (evaluating 'FBLoginManager.login')`
and
`undefined is not a function (evaluating 'FBLoginManager.getCredentials ...`

Are those functions supposed to be working for Android?

**Comment by karega** [comment]
I don't believe FBLoginManager is working on Android.  I'm not aware if this module works on android at all?

**Comment by ignivanishant** [comment]
undefined is not an object (evaluating 'ShareDialog.canShow'

**Comment by ignivanishant** [comment]
i am using  
import { ShareDialog } from 'react-native-fbsdk';

 const shareLinkContent = {
      contentType: 'link',
      contentUrl: "https://facebook.com",
      contentDescription: 'Facebook sharing is easy!',
    };
    
    ShareDialog.canShow(shareLinkContent).then(
      function(canShow) {
          if (canShow) {
            return ShareDialog.show(shareLinkContent);
          }
        }
      ).
      then(
        function(result) {
          if (result.isCancelled) {
            alert('Share operation was cancelled');
          } else {
            alert('Share was successful with postId: '
              + result.postId);
          }
        },
        function(error) {
          alert('Share failed with error: ' + error.message);
        }
      )
      .catch((error) => {
                    alert(error);
    });
 this code inside my on click function can any one please help out
