### ISSUE TITLE
[iOS] App crashes when clicked on the button

### ISSUE THREAD

**Issue by mihir-harbinger** [magus/react-native-facebook-login#97]
![screen shot 2016-03-03 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/17466938/13490633/d8ba4736-e153-11e5-84ab-5d4422621a4a.png)
I followed the setup instructions for android as well as for iOS. It works fine with android, but iOS app crashes after click. The xcode console dumps following errors:

```
2016-03-03 15:12:37.313 [info][tid:main][RCTPerformanceLogger.m:29] Unbalanced calls start/end for tag 5
2016-03-03 15:12:38.642 commonDemo[4313:111586] *** Terminating app due to uncaught exception 'InvalidOperationException', reason: 'fb1553809064910764 is not registered as a URL scheme. Please add it in your Info.plist'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104111e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000103311deb objc_exception_throw + 48
	2   commonDemo                          0x0000000102a56973 +[FBSDKInternalUtility topMostViewController] + 0
	3   commonDemo                          0x0000000102b62c3c -[FBSDKLoginManager logInParametersWithPermissions:] + 82
	4   commonDemo                          0x0000000102b63129 -[FBSDKLoginManager logInWithBehavior:] + 50
	5   commonDemo                          0x0000000102b630e1 -[FBSDKLoginManager logInWithPermissions:handler:] + 238
	6   commonDemo                          0x0000000102b61dff -[FBSDKLoginManager logInWithReadPermissions:fromViewController:handler:] + 257
	7   commonDemo                          0x0000000102b5e8cd -[FBSDKLoginButton _buttonPressed:] + 1082
	8   UIKit                               0x0000000105a3b194 -[UIApplication sendAction:to:from:forEvent:] + 92
	9   UIKit                               0x0000000105baa6fc -[UIControl sendAction:to:forEvent:] + 67
	10  UIKit                               0x0000000105baa9c8 -[UIControl _sendActionsForEvents:withEvent:] + 311
	11  UIKit                               0x0000000105ba9af8 -[UIControl touchesEnded:withEvent:] + 601
	12  UIKit                               0x0000000105aaa49b -[UIWindow _sendTouchesForEvent:] + 835
	13  UIKit                               0x0000000105aab1d0 -[UIWindow sendEvent:] + 865
	14  UIKit                               0x0000000105a59b66 -[UIApplication sendEvent:] + 263
	15  UIKit                               0x0000000105a33d97 _UIApplicationHandleEventQueue + 6844
	16  CoreFoundation                      0x000000010403da31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	17  CoreFoundation                      0x000000010403395c __CFRunLoopDoSources0 + 556
	18  CoreFoundation                      0x0000000104032e13 __CFRunLoopRun + 867
	19  CoreFoundation                      0x0000000104032828 CFRunLoopRunSpecific + 488
	20  GraphicsServices                    0x0000000107ed1ad2 GSEventRunModal + 161
	21  UIKit                               0x0000000105a39610 UIApplicationMain + 171
	22  commonDemo                          0x0000000102a3dfcf main + 111
	23  libdyld.dylib                       0x000000010770692d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by miknonny** [comment]
That error message is really misleading. Had a similar issue. Make sure to cross check your `info.plist` with the one in the example. Its the most likely culprit..

**Comment by mihir-harbinger** [comment]
The app shows following error.
`RCTFBLoginManager.getCredentials() was not found. ` 
Does that help? 

Meanwhile, I'll go through info.plist and get back to you in some time.

**Comment by sethx** [comment]
This fixed it for me:

```		
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fbxxxxxxxxxxxxxxxx</string>
			</array>
		</dict>
	</array>
```

get that fbxxxxxx string from your error.

**Comment by magus** [comment]
Seems like this issue is resolved by ensuring your info.plist is correct? Let me know if not!

**Comment by mihir-harbinger** [comment]
@magus Yes! My info.plist was wrong. I had not removed `{ }` from facebook app id. Thanks @sethx for the clue.

**Comment by sunlee-newyork** [comment]
For anyone still having issues, just copy/paste and follow the instructions from the [Facebook iOS documentation](https://developers.facebook.com/docs/ios/getting-started#xcode)

```
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>fb{your-app-id}</string>
    </array>
  </dict>
</array>
<key>FacebookAppID</key>
<string>{your-app-id}</string>
<key>FacebookDisplayName</key>
<string>{your-app-name}</string>
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>fbapi</string>
  <string>fb-messenger-share-api</string>
  <string>fbauth2</string>
  <string>fbshareextension</string>
</array>
```
